import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact MyApp",
  description: "Generated by create next app",
};

export default function ContactLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <div>
      {children}
    </div>
  );
}
