import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About MyApp",
  description: "Generated by create next app",
};

export default function AboutLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <div className=" ">
      {children}
    </div>
  );
}
