import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: "Pricing MyApp",
  description: "Generated by create next app",
};

export default function PricingLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <div className=" ">
      {children}
    </div>
  );
}
